name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go install

    - name: Build rescue.exe
      run: go build -v -o rescue.exe cmd/rescue/main.go

    - name: Build spike1.exe
      run: go build -v -o spike1.exe spikes/spike1/main.go

    - name: Build spike2.exe
      run: go build -v -o spike2.exe spikes/spike2/main.go

    - name: Test
      run: go test -v ./...

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: ExeFiles
        path: ./**/*.exe
