name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go install

    - name: Build rescue.exe
      run: go build -v -o rescue.exe main.go

    - name: Build spike1.exe
      run: go build -v -o spike1.exe examples/spike1/main.go

    - name: Build spike2.exe
      run: go build -v -o spike2.exe examples/spike2/main.go

    - name: Build spike3.exe
      run: go build -v -o spike3.exe examples/spike3/main.go

    - name: Build spike4.exe
      run: go build -v -o spike4.exe examples/spike4/main.go

    - name: Build spike6.exe
      run: go build -v -o spike6.exe examples/spike6/main.go

    - name: Build spike7.exe
      run: go build -v -o spike7.exe examples/spike7/main.go

    - name: Test
      run: go test -v ./...

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: RescueBundle
        path: |
          *.exe
          assets/
          json/
