name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        challenge: [1, 2, 3, 4, 6]

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go install

    - name: Build rescue.exe
      run: go build -v -o rescue.exe main.go

    - name: Build spike${{ challenge }}.exe
      run: go build -v -o spike${{ challenge }}.exe examples/spike${{ challenge }}/main.go

    - name: Test
      run: go test -v ./...

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: RescueBundle
        path: |
          *.exe
          assets/
          json/
